services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: churn-prediction-api
    ports:
      - "8000:8000"
    environment:
      - MODEL_URI=models:/customer_churn_model@champion 
      - MLFLOW_TRACKING_URI=http://mlflow_server:5000
      - MLFLOW_S3_ENDPOINT_URL=http://172.18.0.3:9000
      - AWS_ACCESS_KEY_ID=admin
      - AWS_SECRET_ACCESS_KEY=admin123
      - AWS_DEFAULT_REGION=us-east-1
    volumes:
      - ./api/data:/app/api/data
      - ./api/reports:/app/api/reports
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - aio-network

  ui:
    build:
      context: .
      dockerfile: Dockerfile.ui
    container_name: churn-prediction-ui
    restart: unless-stopped
    ports:
      - "7860:7823"
    environment:
      - API_BASE_URL=http://api:8000
    depends_on:
      - api
    networks:
      - aio-network


networks:
  aio-network:
    external: true